# Generated by Django 5.0.4 on 2024-04-30 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "brand",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="product",
            table="product",
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.brand",
            ),
        ),
    ]
